### ISSUE TITLE
`flutter run` doesn't work for the Gallery app

### ISSUE THREAD

**Issue by gedw99** [google/flutter.widgets#13]
run script:
````
# cleanup
	cd $(FLU_EX_FSPATH) && flutter clean

	flutter emulators
	flutter emulators --launch apple_ios_simulator
	#flutter emulators --launch Pixel_2_API_28
	
	#cd $(FLU_EX_FSPATH) && flutter run -d all
	cd $(FLU_EX_FSPATH) && flutter run 

````

Crash log:

````
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/apple/workspace/go/src/github.com/google/flutter.widgets/gallery/ios/Runner.xcodeproj/project.pbxproj' (OS Error: No such file or directory, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.2.0, on Mac OS X 10.14.3 18D42, locale en-DE)
    [32m•[39m Flutter version 1.2.0 at /Users/apple/workspace/flutter/flutter_macos_v0.2.8-beta/flutter
    [32m•[39m Framework revision 06b979c4d5 (7 days ago), 2019-01-25 14:27:35 -0500
    [32m•[39m Engine revision 36acd02c94
    [32m•[39m Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/apple/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/apple/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [31m✗[39m Android license status unknown.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 32.0.1
    [32m•[39m Dart plugin version 182.5124
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.30.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.22.3

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 8 Plus • 356EB044-F3C1-45CA-9CEE-C5A5BCC933A0 • ios • iOS 12.1 (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by jamesderlin** [comment]
What is `$(FLU_EX_FSPATH)`?

I assume you're trying to run `flutter run` from the `flutter.widgets/gallery`.  Yes, I've run into this too.  Basically we don't include the Android or iOS project files.  From the `flutter.widgets/gallery` directory, you can just run `flutter create .` first.

I think we should just explain this in the documentation.

**Comment by gedw99** [comment]
make sense. thanks @jamesderlin
