### ISSUE TITLE
scrollable_positioned_list scroll not working on latest Flutter's master

### ISSUE THREAD

**Issue by Zazo032** [google/flutter.widgets#160]
## Problem description
We have a modal bottom sheet that, on its `initState`, calculates the amount of offset to scroll (using `scrollTo`). On latest versions of Flutter, instead of scrolling, the following error is thrown: 

```
I/flutter (23397): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23397): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (23397): The method 'toDouble' was called on null.
I/flutter (23397): Receiver: null
I/flutter (23397): Tried calling: toDouble()
I/flutter (23397): 
I/flutter (23397): When the exception was thrown, this was the stack:
I/flutter (23397): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (23397): #1      int./ (dart:core-patch/integers.dart:28:36)
I/flutter (23397): #2      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:scrollable_positioned_list/src/positioned_list.dart:321:53)
I/flutter (23397): #3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1114:15)
I/flutter (23397): #4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1061:9)
I/flutter (23397): #5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:969:5)
I/flutter (23397): #9      _invoke (dart:ui/hooks.dart:253:10)
I/flutter (23397): #10     _drawFrame (dart:ui/hooks.dart:211:3)
I/flutter (23397): (elided 3 frames from dart:async)
I/flutter (23397): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (23397): https://api.airhopping.com/explore/calendar/VIE/?origin=ALC&month=2020-09%2C2020-10&adults=1&infants=0&children=0&cabin_bags=0&lang=es
I/flutter (23397): Error caught by Crashlytics plugin <recordError>:
I/flutter (23397): NoSuchMethodError: The method '_mulFromInteger' was called on null.
I/flutter (23397): Receiver: null
I/flutter (23397): Tried calling: _mulFromInteger(2)
I/flutter (23397): 
I/flutter (23397): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (23397): #1      int.* (dart:core-patch/integers.dart:16:38)
I/flutter (23397): #2      _ScrollablePositionedListState._startScroll (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:439:47)
I/flutter (23397): #3      _ScrollablePositionedListState._scrollTo (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:407:13)
I/flutter (23397): #4      ItemScrollController.scrollTo (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:193:33)
I/flutter (23397): #5      _CalendarWidgetState.initState.<anonymous closure>.<anonymous closure> (package:airhopping/widgets/parameters_buttons/widgets/dates_widget/widgets/calendar_widget/calendar_widget.dart:61:32)
I/flutter (23397): #6      new Future.delayed.<anonymous closure> (dart:async/future.dart:325:39)
I/flutter (23397): #7      _rootRun (dart:async/zone.dart:1182:47)
I/flutter (23397): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter (23397): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter (23397): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart
```

Note that the call to `scrollTo` is made inside `initState` like this:
```dart
super.initState();
_itemScrollController = ItemScrollController();
_itemPositionsListener = ItemPositionsListener.create();
WidgetsBinding.instance.addPostFrameCallback((duration) {
  Future.delayed(const Duration(milliseconds: 250), () {
    _itemScrollController?.scrollTo(...);
  });
});
```

## Steps to reproduce

1. Run the example app on latest Flutter `master` channel.
2. See the logs:
```
I/flutter (23397): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23397): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (23397): The method 'toDouble' was called on null.
I/flutter (23397): Receiver: null
I/flutter (23397): Tried calling: toDouble()
I/flutter (23397): 
I/flutter (23397): When the exception was thrown, this was the stack:
I/flutter (23397): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (23397): #1      int./ (dart:core-patch/integers.dart:28:36)
I/flutter (23397): #2      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:scrollable_positioned_list/src/positioned_list.dart:321:53)
I/flutter (23397): #3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1114:15)
I/flutter (23397): #4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1061:9)
I/flutter (23397): #5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
I/flutter (23397): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (23397): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

## Expected behavior
The content scrolls.

## Actual behavior
An error is thrown and no scroll is made.

## Environment
Scroll works on `dev`:
```
Flutter 1.21.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f25bd9c55c (12 days ago) • 2020-07-14 20:26:01 -0400
Engine • revision 99c2b3a245
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

But does not work on `master`:
```
Flutter 1.21.0-6.0.pre.38 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8e0eee9008 (3 hours ago) • 2020-07-26 23:38:01 -0700
Engine • revision 626244a72c
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev a3815b6590)
```

cc/ @tarobins

**Comment by tarobins** [comment]
Just published an update in 1.7.0.

Please let me know if it's still an issue.

**Comment by Zazo032** [comment]
Thanks fot the quick fix Tom! It's working as intended now again 🥇

**Comment by 5inline** [comment]
This seems to have returned with Flutter 1.22.0. I'm guessing it is because of the changes they made with scrolling/keyboard?

```
I/flutter (31177): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (31177): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (31177): The method 'toDouble' was called on null.
I/flutter (31177): Receiver: null
I/flutter (31177): Tried calling: toDouble()
I/flutter (31177):
I/flutter (31177): When the exception was thrown, this was the stack:
I/flutter (31177): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5))
I/flutter (31177): #1      int./  (dart:core-patch/integers.dart:28:36))
I/flutter (31177): #2      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> 
package:flutter_widgets/…/src/positioned_list.dart:319
I/flutter (31177): #3      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
I/flutter (31177): #4      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1063
I/flutter (31177): #5      SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:971
I/flutter (31177): #9      _invoke  (dart:ui/hooks.dart:251:10))
I/flutter (31177): #10     _drawFrame  (dart:ui/hooks.dart:209:3))
I/flutter (31177): (elided 3 frames from dart:async)
I/flutter (31177): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by schultz9998** [comment]
Flutter 1.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f30b7f4db9 (2 days ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1

```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      int./ (dart:core-patch/integers.dart:28:36)
#2      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:flutter_widgets/src/scrollable_positioned_list/src/positioned_list.dart:319:53)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
```

**Comment by tarobins** [comment]
@schultz9998 can you please check [here](https://github.com/google/flutter.widgets/issues/183#issuecomment-705602475) and see if that solved your issue?

**Comment by tarobins** [comment]
@5inline can you also check that too please?

**Comment by schultz9998** [comment]
@tarobins yes, it does fixes it. Thank you very much.

**Comment by 5inline** [comment]
> @5inline can you also check that too please?

Yes, that fixed it for me as well. Thank you.
