### ISSUE TITLE
Got NaN exception when first time scrolling to beginning or end of list

### ISSUE THREAD

**Issue by JmyW** [google/flutter.widgets#173]
It's happened the following exception at first time scrolling to beginning or end of list.

Steps:
1. When scroll list is appeared.
2. Swipe right to scroll to the beginning of list
    or Swipe left to scroll to the end of list 
3. Got the following NaN exception

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following UnsupportedError was thrown during a scheduler callback:
Unsupported operation: Infinity or NaN toInt

When the exception was thrown, this was the stack: 
#0      double.toInt (dart:core-patch/double.dart:192:36)
#1      double.round (dart:core-patch/double.dart:160:34)
#2      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:scrollable_positioned_list/src/positioned_list.dart:334:26)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1116:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by JmyW** [comment]
I am using "scrollable_positioned_list: ^0.1.7"

**Comment by mig35** [comment]
Hey @JmyW and @tarobins ,

I had the same problem in my project and was able to fix this in this PR (https://github.com/google/flutter.widgets/pull/180), but that I tried to reproduce this issue in the sample to create a test of this fix, but was not able to do this.

@JmyW can you share your reproduce example or at least test my fix in your project?
You can install it by modifying the dependency like this:

```
  scrollable_positioned_list:
    git:
      url: https://github.com/mig35/flutter.widgets
      ref: bugfix/173
      path: packages/scrollable_positioned_list
```

**Comment by JmyW** [comment]
It's weird, I took 3 hours tried previous version I did backup. I cannot reproduce it any more.
In last two weeks, I keep growing up my program, I did not remembered I've ever seen it in past two weeks. Since your request, I rollback to my backup codes, it is also unduplicated. I even tried to write a new program with the scrolling, but same. 

I'm sorry I couldn't confirm it for you.

**Comment by justkawal** [comment]
@JmyW I thinks that the issue is in package : **scrollable_positioned_list**

**Comment by shushper** [comment]
I have the same issue. Version 0.1.8.

Steps:
1. Scroll to position with  `itemScrollController.jumpTo(index: itemPosition)`
2. Scroll list with a finger. 

```
The following UnsupportedError was thrown during a scheduler callback:
Unsupported operation: Infinity or NaN toInt

When the exception was thrown, this was the stack: 
#0      double.toInt (dart:core-patch/double.dart:192:36)
#1      double.round (dart:core-patch/double.dart:160:34)
#2      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:scrollable_positioned_list/src/positioned_list.dart:324:45)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
```

**Comment by justkawal** [comment]
which version of **scrollable_positioned_list** u r using ?

**Comment by JmyW** [comment]
I used 0.1.7 for issue creation and retest with same version, no change.

**Comment by JmyW** [comment]
> I used 0.1.7 for issue creation and retest with same version, no change.

Oops, I think you were asking @shushper

**Comment by mig35** [comment]
Also @shushper could you check if my fix work as described here: https://github.com/google/flutter.widgets/issues/173#issuecomment-704673432

**Comment by shushper** [comment]
@justkawal I am using a 0.1.8 version.

@mig35 Yes, your fix works because I made the same fix by myself and it helped. 

The reason for the issue is that through the computation of itemOffset in `_schedulePositionNotificationUpdate` method of `_PositionedListState` class value of itemOffset becomes NaN. I added some logs and found that the problem in the `reveal` variable. 

```
if (widget.scrollDirection == Axis.vertical) {
  final reveal = viewport.getOffsetToReveal(box, 0).offset;
  final itemOffset = reveal -
      viewport.offset.pixels +
      viewport.anchor * viewport.size.height;

  print('Reveal = $reveal');
  print('Viewport Offset = ${viewport.offset.pixels}');
  print('Viewport Anchor = ${viewport.anchor}');
  print('Viewport height = ${viewport.size.height}');
  print('Item offset = $itemOffset');

  positions.add(ItemPosition(
      index: key.value,
      itemLeadingEdge: itemOffset.round() /
          scrollController.position.viewportDimension,
      itemTrailingEdge: (itemOffset + box.size.height).round() /
          scrollController.position.viewportDimension));
 
}
```

When the issue occurs my logs are:
```
I/flutter (10988): Reveal = NaN
I/flutter (10988): Viewport Offset = 757.1581221883587
I/flutter (10988): Viewport Anchor = 0.14921465968586387
I/flutter (10988): Viewport height = 764.0
```

So it seems like we should prevent the `reveal` from being NaN or check its value before the computation of `itemOffsets`

**Comment by tarobins** [comment]
Does someone have a public project where this can be repo'd?  I've been trying with this one https://github.com/tarobins/spl_example_wrapper but no luck yet.
