### ISSUE TITLE
ScrollablePositionedList rebuild with new key CRASHES (not disposing ongoing animations)

### ISSUE THREAD

**Issue by lff5** [google/flutter.widgets#262]
## Problem description
I need to show multiple different scrollable lists inside same (one at a time) and I need to be able to jump to specific index.
There might be better ways of doing this but currently
- to swap out list contents (different elements, with different itemCount) i use key on SPL (as seen in this example)
- to land on correct position I set postFrameCallback with jumpTo inside SPL's build method

And i get occasionally these two errors:
- _ScrollablePositionedListState#03240(tickers: tracking 1 ticker) was disposed with an active Ticker.
- _AssertionError ('package:flutter/src/widgets/framework.dart': Failed assertion: line 4109 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.)

## To reproduce
- run the code below
- click 'scroll and swap' (starts scrollTo animation, delays and then rebuilds with new key)
- code will throw
- click again 'scroll and swap' to get different combination of errors

### Code
```
import 'package:flutter/material.dart';
import 'package:scrollable_positioned_list/scrollable_positioned_list.dart';
import 'dart:math';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<int> heights = [];
  Key key = UniqueKey();
  int startIndex = 100;
  final controller = ItemScrollController();

  @override
  void initState() {
    super.initState();
    Random random = new Random();
    for (int i = 0; i < 500; i++) heights.add(random.nextInt(100) + 30);
  }

  Widget itemBuilderInstant(BuildContext context, int index) {
    return Container(
        color: index % 5 == 0 ? Colors.amber : Colors.white,
        height: heights[index].toDouble(),
        child: Text("Index $index, ${heights[index]}"));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: TextButton(
          onPressed: () {
            controller.scrollTo(
                index: Random().nextInt(heights.length),
                duration: Duration(milliseconds: 500));
            Future.delayed(Duration(milliseconds: 200)).then((value) {
              setState(() {
                key = UniqueKey();
                startIndex = Random().nextInt(heights.length);
              });
            });
          },
          child: Text("scroll and swap")),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerTop,
      body: ScrollablePositionedList.builder(
          itemScrollController: controller,
          initialScrollIndex: startIndex,
          key: key,
          itemCount: heights.length,
          itemBuilder: itemBuilderInstant),
    );
  }
}
```

### console log
There are multiple errors happening that I see in real application one by one separately (not cascading).
```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Xcode build done.                                           35.9s
Connecting to VM Service at ws://127.0.0.1:54253/i4-SPniG0Og=/ws
Reloaded 1 of 557 libraries in 407ms.
Reloaded 1 of 557 libraries in 468ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
_ScrollablePositionedListState#5447d(tickers: tracking 1 ticker) was disposed with an active Ticker.

_ScrollablePositionedListState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by _ScrollablePositionedListState#5447d(tickers: tracking 0 tickers))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure>
#1      new Ticker
#2      new _WidgetTicker
#3      TickerProviderStateMixin.createTicker
#4      new AnimationController
#5      _ScrollablePositionedListState._startScroll.<anonymous closure>.<anonymous closure>
#6      SchedulerBinding._invokeFrameCallback
#7      SchedulerBinding.handleDrawFrame
#8      SchedulerBinding._handleDrawFrame
#12     _invoke (dart:ui/hooks.dart:161:10)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
#14     _drawFrame (dart:ui/hooks.dart:120:31)
(elided 3 frames from dart:async)

When the exception was thrown, this was the stack
#0      TickerProviderStateMixin.dispose.<anonymous closure>
#1      TickerProviderStateMixin.dispose
#2      _ScrollablePositionedListState.dispose
#3      StatefulElement.unmount
#4      _InactiveElements._unmount
...
════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4109 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Element.markNeedsBuild
#3      State.setState
#4      _ScrollablePositionedListState._stopScroll
#5      _ScrollablePositionedListState._startScroll
<asynchronous suspension>
#6      _ScrollablePositionedListState._scrollTo
<asynchronous suspension>

════════ Exception caught by widgets library ═══════════════════════════════════
_ScrollablePositionedListState#03240(tickers: tracking 1 ticker) was disposed with an active Ticker.
════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4109 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Element.markNeedsBuild
#3      State.setState
#4      _ScrollablePositionedListState._stopScroll
#5      _ScrollablePositionedListState._startScroll
<asynchronous suspension>
#6      _ScrollablePositionedListState._scrollTo
<asynchronous suspension>

════════ Exception caught by widgets library ═══════════════════════════════════
_ScrollablePositionedListState#26220(tickers: tracking 1 ticker) was disposed with an active Ticker.
════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 108 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      ScrollController.position
#3      _ScrollablePositionedListState._startScroll
#4      _ScrollablePositionedListState._scrollTo.<anonymous closure>
#5      SchedulerBinding._invokeFrameCallback
#6      SchedulerBinding.handleDrawFrame
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/bin<…>
```

## Environment
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-EE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.0)
[✓] Connected device (2 available)
• No issues found!

Running on iOS Simulator - iPhone Pro Max 12

  scrollable_positioned_list: ^0.2.0-nullsafety.0
  sdk: ">=2.12.0 <3.0.0"

**Comment by lff5** [comment]
Has anyone had time to look into it?
