### ISSUE TITLE
scrollTo (with animation) in some case not scroll to the correct item

### ISSUE THREAD

**Issue by nawaf11** [google/flutter.widgets#274]
## Problem description
Package:
package:scrollable_positioned_list/scrollable_positioned_list.dart

## Steps to reproduce

In some cases scrollTo (with animation) not scroll to the correct item (not even close)

I think 1 of the scenario When user see for example item number 30 and scrollTo get called with item 20 ...

I am calling it in this way:

`_itemScrollController?.scrollTo(index: ayahIndex, duration: Duration(milliseconds: 300), alignment: 0.3);`

_itemScrollController is instance of ItemScrollController

## Environment
Android

## Additional details

There's some crash in scrollable_positioned_list In LogCat happen it could be the reason ..

`======== Exception caught by scheduler library =====================================================
The following UnsupportedError was thrown during a scheduler callback:
Unsupported operation: Infinity or NaN toInt

When the exception was thrown, this was the stack: 
#0      double.toInt (dart:core-patch/double.dart:219:36)
#1      double.round (dart:core-patch/double.dart:182:34)
#2      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:scrollable_positioned_list/src/positioned_list.dart:315:45)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
...
====================================================================================================`

**Comment by Maatteogekko** [comment]
could be related to #247

**Comment by ggirotto** [comment]
Facing the same issue

**Comment by futatalka** [comment]
I'm working with a StickyGroupedListView and I have the same problem, I tried jumpTo and it works as expected but scrollTo has an offset.

**Comment by MattyBoy4444** [comment]
Same issue. scrollTo doesn't work, jumpTo works. It seems all the itemPosition.itemLeadingEdge are zero in _startScroll
