### ISSUE TITLE
[visibility_detector] size.height >= 0': is not true

### ISSUE THREAD

**Issue by yyyy-ltd** [google/flutter.widgets#282]
'package:visibility_detector/src/visibility_detector.dart': Failed assertion: line 205 pos 10: 'size.height >= 0': is not true.

The following assertion was thrown during a task callback:
'package:visibility_detector/src/visibility_detector.dart': Failed assertion: line 205 pos 10: 'size.height >= 0': is not true.

When the exception was thrown, this was the stack: 
#2      _area (package:visibility_detector/src/visibility_detector.dart:205:10)
#3      VisibilityInfo.visibleFraction (package:visibility_detector/src/visibility_detector.dart:156:25)
#4      _BetterPlayerState._buildPlayer.<anonymous closure> (package:better_player/src/core/better_player.dart:276:60)
#5      VisibilityDetectorLayer._fireCallback (package:visibility_detector/src/visibility_detector_layer.dart:268:24)
#6      VisibilityDetectorLayer._processCallbacks (package:visibility_detector/src/visibility_detector_layer.dart:239:13)

**Comment by jamesderlin** [comment]
Please provide a reproduction case, ideally an automated test case.  In what situation should the `size.height` be negative?

**Comment by always-together12** [comment]
Hi, I am having the same issue.
any solutions?

**Comment by jamesderlin** [comment]
Can you provide a reproduction case?

**Comment by always-together12** [comment]
![image](https://user-images.githubusercontent.com/54995513/219171545-ac05f127-5630-45e3-8521-28a11a02d765.png)

**Comment by jamesderlin** [comment]
A screenshot is not code that I can use to reproduce the problem.

**Comment by always-together12** [comment]
not sure how to send the code...

**Comment by always-together12** [comment]
`import 'dart:async';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:visibility_detector/visibility_detector.dart';
import '/widgets/nft/nft_card.dart';
import '/config/style.dart';
import '/models/nft/nft_model.dart';
import '/providers/nft_provider.dart';
import '/services/tools.dart';

class LibraryOwnedNftList extends StatefulWidget{
  final ScrollController? scrollController;
  final ValueNotifier<Nft?> activeNftNotifier;
  const LibraryOwnedNftList({this.scrollController, required this.activeNftNotifier, Key? key}) : super(key: key);

  @override
  State<LibraryOwnedNftList> createState() => _LibraryOwnedNftListState();
}

class _LibraryOwnedNftListState extends State<LibraryOwnedNftList> with AutomaticKeepAliveClientMixin<LibraryOwnedNftList>{
  final RefreshController _refreshController = RefreshController(initialRefresh: true);
  int page = 1;
  List<Nft> nftItems = [];


  Future<void> _onRefresh() async {
    try {
      page = 1;
      nftItems = await context.read<NftProvider>().getMyNFTs(page: page);
      if(mounted){
        _refreshController.resetNoData();
        _refreshController.refreshCompleted();
        setState(() {});
        context.read<NftProvider>().myNftNotifier.value = nftItems;
      }
    } catch (e) {
      _refreshController.refreshCompleted();
      Tools.consoleLog('[LibraryOwnedNftList._onRefresh]$e');
      Tools.showErrorMessage(context, e.toString());
    }
  }

  Future<void> _onLoading() async {
    try {
      page++;
      final newNFTs = await context.read<NftProvider>().getMyNFTs(page: page);
      if (mounted){
        if(newNFTs.isNotEmpty){
          _refreshController.loadComplete();
          setState(() {
            nftItems.addAll(newNFTs);
          });
          context.read<NftProvider>().myNftNotifier.value = [...nftItems];
        }else{
          _refreshController.loadNoData();
        }
      }
    } catch (e) {
      Tools.consoleLog('[LibraryOwnedNftList._onLoading]$e');
      Tools.showErrorMessage(context, e.toString());
    }
  }

  @override
  void dispose() {
    _refreshController.dispose();
    super.dispose();
  }


  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Container(
      margin: const EdgeInsets.only(bottom: kToolbarHeight),
      color: kBackGroundColor,
      child: SmartRefresher(
        controller: _refreshController,
        header: const MaterialClassicHeader(),
        onRefresh: _onRefresh,
        onLoading: _onLoading,
        enablePullDown: true,
        enablePullUp: true,
        child: ListView.builder(
          controller: widget.scrollController,
          itemCount: nftItems.length,
          padding: const EdgeInsets.all(20),
          itemBuilder: (c, i) => VisibilityDetector(
              key: Key('nft_item_visibility_${nftItems[i].id}'),
              child: NftCard(
                nftItems[i],
                key: Key('nft_item_${nftItems[i].id}'),
              ),
              onVisibilityChanged: (v){
                try{
                  if(mounted && v.visibleFraction == 1){
                    widget.activeNftNotifier.value = nftItems[i];
                  }
                }catch(e){
                  Tools.consoleLog('[LibraryOwnedNftList.onVisibilityChanged]$e');
                }
              }
          ),
        ),
      ),
    );
  }
}`

**Comment by jamesderlin** [comment]
I can't reproduce the problem myself, so you need to provide a minimal, complete example that allows other people to reproduce the problem.  I would start by making a copy of your project and removing as much code as you can such that the problem is still reproducible.

**Comment by always-together12** [comment]
can you work on my anydesk?

**Comment by jamesderlin** [comment]
No, sorry.  Please provide a way to reproduce the problem.  Alternatively, you can try to help debug the problem by attaching a debugger (or by temporarily adding `debugPrint` statements) and examining the values of the `widgetBounds` and `clipRect` arguments to `VisibilityInfo.fromRects` in `package:visibility_detector/src/visibility_detector.dart`.

**Comment by always-together12** [comment]
The strange thing is I am using it on 5 pages. but I have the issue on ONLY this page.

**Comment by PaoloGi** [comment]
> The strange thing is I am using it on 5 pages. but I have the issue on ONLY this page.

Hi  "maybe" i was able to fix this by adding a check on the context like this

```
onVisibilityChanged: (info) {
    if(context.mounted && context.size != null){
         //your code that is calling   info.visibleFraction             
    }
 },
```

for me the widget was disposed but the visibilityChanged fired just before and that result in an error beacuse the visibleFraction can't be null

**Comment by PaoloGi** [comment]
"maybe" i fixed this error by adding a check inside the onVisbilityChanged like this

```
onVisibilityChanged: (info) {
   if(context.mounted && info.visibleBounds.size.height > 0){
      //your code calling info.visibleFraction ;                       
   }
},
```
