### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by liulianshanzhu** [google/flutter.widgets#493]
## Problem description
package: scrollable_positioned_list
error: Unsupported operation: Infinity or NaN toInt

## Actual behavior
```
UnsupportedError

Unsupported operation: Infinity or NaN toInt

#0 _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:scrollable_positioned_list/src/positioned_list.dart)

#1 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284)

#2 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1223)

#3 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072)

#4 _rootRun (dart:async/zone.dart:1399)

#5 _CustomZone.run (dart:async/zone.dart:1301)

#6 _CustomZone.runGuarded (dart:async/zone.dart:1209)

#7 _invoke (dart:ui/hooks.dart:144)

#8 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359)

#9 _drawFrame (dart:ui/hooks.dart:112)
```

## Environment

scrollable_positioned_list:0.3.5
Flutter 3.10.6

**Comment by markandrewjaxl** [comment]
Facing the same issue

**Comment by ch1025540473** [comment]
same issue, how to resolve it
