### ISSUE TITLE
ScrollablePositionedList '_scrollableListState != null': is not true.

### ISSUE THREAD

**Issue by nawaf11** [google/flutter.widgets#62]
I am getting crash when the screen which have
ScrollablePositionedList getting closed/disposed (back button)

I am using ChangeNotifierProvider and Consumer pattern.

The error happen after the notifyListeners() in provider get called then I press back button.

the Error:

```
The following assertion was thrown while finalizing the widget tree:
'package:flutter_widgets/src/scrollable_positioned_list/src/scrollable_positioned_list.dart': Failed assertion: line 195 pos 12: '_scrollableListState != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ItemScrollController._detach (package:flutter_widgets/src/scrollable_positioned_list/src/scrollable_positioned_list.dart:195:12)
#3      _ScrollablePositionedListState.dispose (package:flutter_widgets/src/scrollable_positioned_list/src/scrollable_positioned_list.dart:232:34)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4435:12)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1748:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
```

My Code:

```
class AyahListPage extends StatefulWidget {

  Surah surah;

  AyahListPage(this.surah);

  @override
  _AyahListPageState createState() => _AyahListPageState();
}

class _AyahListPageState extends State<AyahListPage> {
  AyahPool_Provider ayahPool_Provider = AyahPool_Provider();

  ItemScrollController itemScrollController;
  ItemPositionsListener itemPositionListener;


  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    MasterProvider masterProvider = Provider.of<MasterProvider>(context);


    return FutureBuilder(
      future: loadTask(),
      builder: (context, snapshot) {

        if(! snapshot.hasData)
          return CircularProgressIndicator();

        return ChangeNotifierProvider<AyahPool_Provider>(
            create: (context) => ayahPool_Provider,
            child: Scaffold(
                appBar: AppBar(title: Text(masterProvider.appTitle)),
                body: Container(margin: EdgeInsets.all(8),
                    child:
                    Consumer<AyahPool_Provider>(
                        builder: (context, provider, _) {

                          var checkBox = CheckboxListTile(title: Text('Trans'),value: provider.ayahMode_withWordTrans,
                            onChanged: (flag) {
                              provider.ayahMode_withWordTrans = flag;
                            },);

                          var checkBox_2 = CheckboxListTile(title: Text('Lemma'),value: provider.ayahMode_withWordLemma,
                            onChanged: (flag) {
                              provider.ayahMode_withWordLemma = flag;
                            },);

                          var pageContent = Column(children: <Widget>[Wrap(children: <Widget>[checkBox, checkBox_2]),
                            Expanded(child: AyahListView(widget.surah))],);

                          return pageContent;


                        }))));

      },
    );



  }

  Future<AyahList> loadTask() async {
    ayahPool_Provider.surah = widget.surah;
    ayahPool_Provider.bislAllah_glyph = await DAO_TB_Glyph.db_getBismallah();
    ayahPool_Provider.ayahList = await DAO_TB_Glyph.db_getBySurah_asAyahList(widget.surah.ID);
    return ayahPool_Provider.ayahList;
  }


   // --------------- Ayah List part ----------------------------

  Widget AyahListView(Surah surah) {
    ayahPool_Provider.addBismAllahItem_ifSurahHave(widget.surah);

    var ayahList_listView = listView_fromAyahList(ayahPool_Provider);

    return ayahList_listView;
  }

  Widget listView_fromAyahList(AyahPool_Provider ayahPool_Provider,
      {double size = Quran_Ui.quranText_defaultSize}) {


    // This is to scroll to specific item (LATER).
    itemScrollController = ItemScrollController(); //TODO: this make bug if i set it.
    itemPositionListener = ItemPositionsListener.create();
    var listView = ScrollablePositionedList.builder(
        itemCount: ayahPool_Provider.ayahList.ayahList.length,
        itemPositionsListener: itemPositionListener,
        itemScrollController: itemScrollController,
        itemBuilder: (BuildContext context, int index) {
          Ayah ayah = ayahPool_Provider.ayahList.ayahList[index];

          if (ayah.translationAndExplaination_mapList != null || ayah.isThisBismallahItem())
            return buildAyahItem(index, ayahPool_Provider, size);

          return FutureBuilder(
              future: loadTransBox(ayahPool_Provider.surah, ayah),
              builder: (context, snapshot) {
                // this will hide the widget if the data still not loaded
                double opacityVal = (snapshot.hasData) ? 1 : 0;
                return Opacity(
                    child: buildAyahItem(
                        index, ayahPool_Provider, size),
                    opacity: opacityVal);
              }
          );
        });

    return listView;

  }
```

**Comment by nawaf11** [comment]
The solution was:

init the ItemScrollController inside: initState() not in build ..

```
  @override
  void initState() {
    itemScrollController = ItemScrollController();
    itemPositionListener = ItemPositionsListener.create();
    super.initState();
  }
```

**Comment by MrVipinVijayan** [comment]
I am calling inside InitState, still this issue happens.

**Comment by UlyssesAlves** [comment]
I need to scroll my list as soon as it's stateful widget parent is built. Does someone have a suggestion on how I could do it?

**Comment by UlyssesAlves** [comment]
I've found some code on StackOverflow which might solve my issue. In case someone else needs something similiar, it's on this page: https://stackoverflow.com/a/51069090/1639385

**Comment by HLGB26** [comment]
I solved this issue by checking condition itemScrollControll.isAttached than calling the itemScrollController.scrollTo() function.

` @override
  void initState() {
    super.initState();
    getIdx();

    scrollController = ItemScrollController();
    itemPositionsListener = ItemPositionsListener.create();

    if(scrollController.isAttached){
      scrollController.scrollTo(
          index: idx,
          duration: Duration(seconds: 2),
          curve: Curves.easeInOutCubic);
    }
  }`

**Comment by vuongquocthanh** [comment]
> I solved this issue by checking condition itemScrollControll.isAttached than calling the itemScrollController.scrollTo() function.
> 
> ` @override
> void initState() {
> super.initState();
> getIdx();
> 
> ```
> scrollController = ItemScrollController();
> itemPositionsListener = ItemPositionsListener.create();
> 
> if(scrollController.isAttached){
>   scrollController.scrollTo(
>       index: idx,
>       duration: Duration(seconds: 2),
>       curve: Curves.easeInOutCubic);
> }
> ```
> 
> }`

This is right solution!

**Comment by felipecastrosales** [comment]
How adjust this in Widget testing? E.g: 
![image](https://user-images.githubusercontent.com/59374587/224190302-e022bb78-208a-483f-859e-51ddc5678903.png)

**Comment by raghavendra-k-j** [comment]
```
 WidgetsBinding.instance.addPostFrameCallback((_) {
        if (selectedLanguageId.value.isNotEmpty) {
          int index = languages.indexWhere((element) => element.id == selectedLanguageId.value);
          if (index != -1) {
            itemScrollController.scrollTo(
              index: index,
              duration: const Duration(milliseconds: 500),
              curve: Curves.easeInOut,
            );
          }
        }
      });
