### ISSUE TITLE
ScrollablePositionedList: Exception when setState

### ISSUE THREAD

**Issue by singun-lxd** [google/flutter.widgets#70]
NullPointer happens when the page is detached from window, ```if (mounted)``` maybe needed.

```
NoSuchMethodError
NoSuchMethodError: The method 'markNeedsBuild' was called on null. Receiver: null Tried calling: markNeedsBuild
1 #0 State.setState (package:flutter/src/widgets/framework.dart:1168)
2 #1 _ScrollablePositionedListState._startScroll.<anonymous closure> (package:flutter_widgets/src/scrollable_positioned_list/src/scrollable_positioned_list.dart:409)
3 #2 _ScrollablePositionedListState._startScroll.<anonymous closure> (package:flutter_widgets/src/scrollable_positioned_list/src/scrollable_positioned_list.dart:420)
4 #3 _rootRunUnary (dart:async/zone.dart:1134)
5 #4 _CustomZone.runUnary (dart:async/zone.dart:1031)
6 #5 _FutureListener.handleValue (dart:async/future_impl.dart:139)
7 #6 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680)
8 #7 Future._propagateToListeners (dart:async/future_impl.dart:709)
9 #8 Future._completeWithValue (dart:async/future_impl.dart:524)
10 #9 Future.wait.<anonymous closure> (dart:async/future.dart:400)
11 #10 _rootRunUnary (dart:async/zone.dart:1134)
12 #11 _CustomZone.runUnary (dart:async/zone.dart:1031)
13 #12 _FutureListener.handleValue (dart:async/future_impl.dart:139)
14 #13 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680)
15 #14 Future._propagateToListeners (dart:async/future_impl.dart:709)
16 #15 Future._completeWithValue (dart:async/future_impl.dart:524)
17 #16 Future.wait.<anonymous closure> (dart:async/future.dart:400)
18 #17 _rootRunUnary (dart:async/zone.dart:1134)
19 #18 _CustomZone.runUnary (dart:async/zone.dart:1031)
20 #19 _FutureListener.handleValue (dart:async/future_impl.dart:139)
21 #20 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680)
22 #21 Future._propagateToListeners (dart:async/future_impl.dart:709)
23 #22 Future._completeWithValue (dart:async/future_impl.dart:524)
24 #23 Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554)
25 #24 _rootRun (dart:async/zone.dart:1126)
26 #25 _CustomZone.run (dart:async/zone.dart:1023)
27 #26 _CustomZone.runGuarded (dart:async/zone.dart:925)
28 #27 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
29 #28 _microtaskLoop (dart:async/schedule_microtask.dart:43)
30 #29 _startMicrotaskLoop (dart:async/schedule_microtask.dart:52)
```

**Comment by tarobins** [comment]
@singun-lxd 
Do you have some sample code to demo this problem?

**Comment by singun-lxd** [comment]
> @singun-lxd
> Do you have some sample code to demo this problem?

@tarobins  Sorry, it just happened in my app's user environment, I cannot reproduce it.
It never happen again after I add `if (mounter)` condition
